name: analyse and test

on: 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2.5.0
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze

      - name: Install very_good cli
        run: dart pub global activate very_good_cli

      - name: Run tests
        run: very_good test
      
     

